### ISSUE TITLE
Optional dependency on react-native-blur

### ISSUE THREAD

**Issue by brentvatne** [lelandrichardson/react-native-parallax-view#1]
Would be useful if the require isn't used until it is needed, so if you decide to enable blur it will require it and throw an error but you can otherwise use it without blur.

**Comment by lelandrichardson** [comment]
@brentvatne great point!

I haven't thought much about on-demand requiring and how to do it efficiently, this seems like it will work well to me. Any thoughts?

https://github.com/lelandrichardson/react-native-parallax-view/commit/135a586fd32a33734609d52995b3635e16a5463b

**Comment by brentvatne** [comment]
@lelandrichardson - yeah that looks like it should work just fine! nice

**Comment by brentvatne** [comment]
also @lelandrichardson, check [this out](https://appetize.io/embed/dhw0pbp14v89w60quwrj6w70dg?device=iphone5s&scale=100&autoplay=false&orientation=portrait&deviceColor=black&params=%7B%22appId%22:%22qAFzcA%22,%22moduleName%22:%22ParallaxExample%22%7D) :smile:

**Comment by lelandrichardson** [comment]
@brentvatne you can get this with version 1.0.2 on npm now btw. closing.

**Comment by lelandrichardson** [comment]
@brentvatne man. I really need to figure out how to use appetize.io. That's awesome!
