### ISSUE TITLE
contentInset.top does not work correctly

### ISSUE THREAD

**Issue by jaulz** [lelandrichardson/react-native-parallax-view#10]
In order to make my header smaller I found the contentInset.top property. Though it works when first rendered after scrolling it does not work correctly anymore and you see a gap between the header and the content.

**Comment by lelandrichardson** [comment]
@jaulz  Please try updating to the new version and let me know if this is still a problem. Thanks.

**Comment by askday** [comment]
I meet this problem,too
when first open view ,that's renderd correctly
but I scroll it ,the header scroll to the top
you can see it through statesbar

![t1](https://cloud.githubusercontent.com/assets/11714758/12506058/0eaae762-c127-11e5-89b2-aa46863e8836.png)
![t2](https://cloud.githubusercontent.com/assets/11714758/12506059/0eaea3e8-c127-11e5-9c80-3ca45860cc6d.png)

**Comment by ericraio** [comment]
+1 having the same issue too as well

**Comment by ericraio** [comment]
@lelandrichardson there is no fix in the latest version for this. :/

**Comment by williambout** [comment]
+1 I have the same issue.

**Comment by askday** [comment]
I solve this problem by change contentInset.top when view getDefaultProps.

`
getDefaultProps: function () {
        return {
            windowHeight: 300,
            contentInset: {
                top: 5 * screen.scale
            }
        };
    },
`
