### ISSUE TITLE
windowHeight needs to be declared above header

### ISSUE THREAD

**Issue by rkho** [lelandrichardson/react-native-parallax-view#12]
I'm running into an error when `windowHeight` is declared below `header`. React Native throws the following error:

![screenshot 2015-06-15 15 47 30](https://cloud.githubusercontent.com/assets/4451985/8172485/dc880ba2-1375-11e5-89a2-62aabe9c8adc.png)

Here's how my code block for rendering looks:

```
      <ParallaxView
        backgroundSource={{uri: this.state.collection.background_image_url}}
        header={(
          <Text>
            {this.state.collection.title}
          </Text>
          )}
        windowHeight={200}
        >
        <ListView
          dataSource={this.state.dataSource}
          renderRow={this.renderPostCell}
          style={styles.postsListView} />
      </ParallaxView>
```

If I move `windowHeight` above `header`, this issue does not come up.

`README.md` for this repo currently suggests `windowHeight` being placed **below** `header`, which produces this issue for me.

I've made a PR to update `README.md` here: #11

**Comment by lelandrichardson** [comment]
closed. thanks!
