### ISSUE TITLE
Where's the source to the Demo GIF?

### ISSUE THREAD

**Issue by hokster7** [lelandrichardson/react-native-parallax-view#13]

**Comment by lelandrichardson** [comment]
finally getting some time for this. give me a day or two.

**Comment by hokster7** [comment]
@lelandrichardson No pressure :)

**Comment by lelandrichardson** [comment]
@fatuhoku I've updated the repo to use the new Animated API. The big catch is that it requires >=0.8.0, and as a result, I've upped the npm version number to 2.0.

I've included a full working example project in the repo, and will update the appetize link to an rnplay.org link as soon as rnplay.org supports 0.8.0

Cheers!
