### ISSUE TITLE
Example project doesn't compile out of the box

### ISSUE THREAD

**Issue by hokster7** [lelandrichardson/react-native-parallax-view#14]
![screen shot 2015-07-16 at 14 33 13](https://cloud.githubusercontent.com/assets/430233/8724096/a446cf2a-2bc7-11e5-8be8-6c06729d9d6e.png)

**Comment by lelandrichardson** [comment]
@fatuhoku remember to run `npm install` on the example folder separately in order to get this working.

I've added a note for this in the README. closing this now but feel free to re-open if you're still having issues

**Comment by hokster7** [comment]
Hi @lelandrichardson, after wrestling with installing RN 0.8-rc for a while, I've finally got the example running! Thanks. The example looks fantastic.
