### ISSUE TITLE
Running npm install on Example project does not succeed

### ISSUE THREAD

**Issue by hokster7** [lelandrichardson/react-native-parallax-view#15]
I followed [the steps here to install React Native 0.8.0-rc](https://github.com/facebook/react-native/releases).

When I do `cd react-native-parallax-view; npm install` I get the error:

``` node
npm WARN peerDependencies The peer dependency react-native included from react-native-parallax-view will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-native@>= 0.4 || 0.5.0-rc1 || 0.6.0-rc included from react-native-blur will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/Cellar/iojs/2.3.1/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v2.3.1
npm ERR! npm  v2.7.6
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-blur@0.5.3 wants react-native@>= 0.4 || 0.5.0-rc1 || 0.6.0-rc

npm ERR! Please include the following file with any support request:
npm ERR!     ~/Development/foreign/react-native-parallax-view/npm-debug.log
```

i.e. `react-native-blur-view` doesn't depend on 0.8-rc.

The workaround is to remove the dependency on `react-native-blur-view` for now.

**Comment by lelandrichardson** [comment]
man. I really wish NPM had a way to include the "-rc" branches in a semver selector.  "react-native@0.8.0-rc1" should really satisfy "react-native@>=0.4.0".

I wonder how I was able to get past this requirement on my local version? I just downloaded the repo separately and I do indeed see the same error as you.

I suppose I will temporarily remove the blur view dependency...

**Comment by lelandrichardson** [comment]
I just upped the version number and published to npm. try it now!

**Comment by hokster7** [comment]
@lelandrichardson Unbelievable... Cocoapods supports these, I believe. I've found that `react-native-linear-gradient` depends on `react-native@>=0.4.4`, which once again, `react-native@0.8-rc` does not satisfy. This makes working with release candidates virtually impossible if you have any dependencies at all!
