### ISSUE TITLE
Decorate with react-native-scrollable-decorator in order to support scrollTo

### ISSUE THREAD

**Issue by hokster7** [lelandrichardson/react-native-parallax-view#16]
Hi, I would like to programmatically scroll the scrollView to a specific position with `scrollTo`. This requires exposing the underlying scrollView. [`react-native-scrollable-decorator`](https://github.com/exponentjs/react-native-scrollable-decorator) is probably a good way to do this?

**Comment by lelandrichardson** [comment]
@fatuhoku I think this is a good idea, but I'd recommend we not change the implementation to ES6 classes yet, and instead just use the [mixin version](https://github.com/exponentjs/react-native-scrollable-mixin)

I'm using ES6 classes almost exclusively now in my React.js projects, but I've seen some general aversion to doing so in the react-native project (for whatever reason), where it seems `React.createClass` may still be the preferred method.

This would also have the benefit of not changing so much of the implementation. That said, if I'm wrong about the aversion to ES6 classes, i'm happy to accept that PR as well...

**Comment by hokster7** [comment]
Yep fair enough! I only learned about decorators yesterday so wasn't sure which one to go for. Whichever way makes scrollTo work, basically. I was running into unfamiliar ground using decorators. I'll try out the mix in when I have time.
