### ISSUE TITLE
UnableToResolveError: Unable to resolve module Dimensions

### ISSUE THREAD

**Issue by atom2ueki** [lelandrichardson/react-native-parallax-view#26]
in ParallaxView.js
`var screen = require('Dimensions').get('window');` 
should replaced with
`var screen = Dimensions.get('window');` and add `Dimensions` inside react required objects

react-native version ^0.14.2
- found a pull-request: https://github.com/lelandrichardson/react-native-parallax-view/pull/22

**Comment by dsibiski** [comment]
It looks like the PR was already merged but the latest version with the fix has not been published to NPM. /cc @lelandrichardson

**Comment by jherr** [comment]
:+1: to push this out to NPM. This is a great component, but it's not compatible with RN 0.15 today.

**Comment by lelandrichardson** [comment]
My apologies for this not getting published. I just published master under 2.0.3.

I've been crazy sidetracked with work, and will try my best to dig into some of these issues and maintain this project better in the next couple of weeks.

Thanks, everyone!
