### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [lelandrichardson/react-native-parallax-view#6]
I have noticed that the performance is not optimal compared to that of a ScrollView. I know re-rendering a view with React is meant to be inexpensive. I wonder if that is still the case with RN?

**Comment by lelandrichardson** [comment]
What version of RN are you using?  I've noticed the performance has varied a bit by version, though I'm not sure why.

I am going to push a fix soon that just uses `setNativeProps` inside of `requestAnimationFrame` and I think that that should bring essentially optimal performance.

Thanks

**Comment by deanmcpherson** [comment]
@lelandrichardson I have been having a play with implementing the above in  requestAnimationFrame, but I think it's probably best to keep the setNativeProps in the onScroll callback, as the scroll position will only be updated then anyway (unless you're going to lookup the current scroll position outside of the event? Not sure how that works).

Best performance I've seen so far is using setNativeProps as implemented (commented out in ParallaxView.js) and dropping the scrollEventThrottle to 10 as opposed to 16. I figure 16ms is a 60fps frame, but it will optimistically take a couple of milliseconds to be rendered.

**Comment by lelandrichardson** [comment]
@deanmcpherson Interesting approach using 10ms as opposed to 16...  I tried using requestAnimationFrame a couple of different ways and never had great luck. As a result, I've moved the entire component to use the new Animated API which has considerably better performance.  This update is now on NPM with version number 2.0.  As a result, i'm closing this issue...
